### ISSUE TITLE
Questions at  24H2

### ISSUE THREAD

**Issue by rdfsource** [AiursoftWeb/Safe-Windows#1]
你好，当我使用 Windows11 24H2 （内部版本26100.2033）时，我已执行最新的Windows更新操作
命令行执行时，出现一些奇怪的报错 ：

“无法将“wmic”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。”

我将附上相应截图，以供参考

![safe-windows](https://github.com/user-attachments/assets/aba1cf61-48af-4892-a358-0f114d539578)

**Comment by Anduin2017** [comment]
Update detection is based on the following PowerShell:

```powershell
    $updateTimes = wmic qfe get InstalledOn | Where-Object { $_ -match "[0-9]/" } | ForEach-Object { $_.ToString().Trim() }
    $mostRecentUpdateTime = $updateTimes | Sort-Object -Descending | Select-Object -First 1
    $recentMonthInstalledAnUpdate = $mostRecentUpdateTime -gt (Get-Date).AddDays(-45)
```

However seems your machine doesn't have `wmic` installed.

I'm planning to refactor the PowerShell as follow:

```powershell
$updateTimes = Get-HotFix | Select-Object -ExpandProperty InstalledOn
$mostRecentUpdateTime = $updateTimes | Sort-Object -Descending | Select-Object -First 1
$recentMonthInstalledAnUpdate = $mostRecentUpdateTime -gt (Get-Date).AddDays(-45)
$recentMonthInstalledAnUpdate
```

Do you mind helping executing the PowerShell above and share me the result?

**Comment by rdfsource** [comment]
Yes, here is the result.

![safe-windows-testcode](https://github.com/user-attachments/assets/3a7a7974-1b3f-42ff-bc6c-d291cc79c5bd)

**Comment by Anduin2017** [comment]
Committed as https://github.com/AiursoftWeb/Safe-Windows/commit/192059258174ad01e8e21608a99720865f94db1e

Please try running this project again.

**Comment by rdfsource** [comment]
Yes,  when i UPDATE project and run ' .\Run.ps1', code told me the right things.  

![safe-windows-2](https://github.com/user-attachments/assets/6f0db671-6438-493a-a3b0-94494c403c33)


However , when i using fast  code after   'Then copy the following command and paste it into the PowerShell window. Then press Enter.'  It still not work on the latest  version.

![Q2](https://github.com/user-attachments/assets/788d9541-2a9b-4d2f-9eb2-ac0d471b615b)

**Comment by Anduin2017** [comment]
![image](https://github.com/user-attachments/assets/b56f9946-78e7-4ce6-a91f-4832f9e5c789)

Not my fault.

**Comment by rdfsource** [comment]
Yours , links at [README.md](https://github.com/AiursoftWeb/Safe-Windows/blob/master/README.md), isn't updated!

当我用文件内的.\Run.ps1时,操作结果正常, 当我使用README.md 页面中的代码时, 依旧出现wmic 问题提示

![q1q1q](https://github.com/user-attachments/assets/c3b9f3a0-4b01-4886-94ac-b4cf70203bb2)
